### ISSUE TITLE
스타일가이드 작성

### ISSUE THREAD

**Issue by klmyoungyun** [mash-up-kr/SeeYouAgain_iOS#14]
## 💡 요약

또보겠지에서 사용 할 SwiftUI와 TCA의 스타일 가이드를 작성합니다. with @AhnSangHee 

## ✅ 체크포인트

추가해야 할 규칙이 있으면 알려주세요.

- 코드 레이아웃
    - 들여쓰기 및 띄어쓰기
    - 임포트
    - 개행
    - 줄바꿈
    - 최대 행 길이
- 네이밍
    - 일반
    - 구조체 및 클래스
    - 함수
    - 프로토콜
- 코드 스타일
    - 클로저
    - 구조체 및 클래스
    - 열거형
    - 타입

## 💻 Task

- [x] 스타일가이드 작성

**Comment by klmyoungyun** [comment]
[위키 바로가기!](https://github.com/mash-up-kr/SeeYouAgain_iOS/wiki/SeeYouAgain-SwiftUI-TCA-Style-Guide)

**Comment by AhnSangHee** [comment]
기타 컨벤션, 설치 가이드도 모두 위키에서 볼 수 있습니당~.~

➡️ [🍡또보겠지🍡 위키](https://github.com/mash-up-kr/SeeYouAgain_iOS/wiki)

**Comment by GREENOVER** [comment]
@klmyoungyun @AhnSangHee 
요 이슈 완료되었으면 클로즈 부탁드립니다~🙋🏻
