### ISSUE TITLE
중복 저장 토스트 메세지 수정

### ISSUE THREAD

**Issue by klmyoungyun** [mash-up-kr/SeeYouAgain_iOS#148]
## 💡 요약
중복 저장 토스트 메세지 수정합니다.
 
## ✅ 체크포인트

- 토스트 메세지

## 💻 Task

- [x] 실패 토스트 메세지 분리
- [x] onDisappear에서 토스트메시지 nil

**Comment by GREENOVER** [comment]
간헐적으로 onDisappear 시 토스트 메시지 사라지지 않고 계속 노출되는 현상도 해당 이슈에서 같이 처리해주시면 감사하겠습니다 🙏🏻
