### ISSUE TITLE
오늘의 숏스 다읽음 처리 시 숏스 갯수 업데이트 되지 않는 현상

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/SeeYouAgain_iOS#171]
## 💡 요약
- https://www.notion.so/writing-c6766db2b6be473a97d4946c71453676?pvs=4
- 오늘의 숏스 다읽었어요 처리 시 숏스 갯수가 여전히 읽음 처리전 갯수로 업데이트 되지 않음

## ✅ 체크포인트
- 오늘의 숏스 다읽음 처리 시 숏스 갯수 업데이트 되지 않는 현상

## 💻 Task
- [ ] 업데이트 반영 필요

**Comment by GREENOVER** [comment]
<img width="433" alt="스크린샷 2023-07-16 오전 9 30 32" src="https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/72292617/055026a5-82b7-4dd9-8a68-22307c15c4d2">
- 다읽음 처리 외에도 위와 같이 동기화 되지 않음

**Comment by klmyoungyun** [comment]
**"오늘은 아직 저장한 뉴스가 없어요"** 가 아닌 **"오늘 저장한 뉴스를 다 읽었어요"** 를 잘못 보여주는 문제는 해결해서 커밋했습니다!
+) 형이 코멘트한 동기화 문제는 어떤건가요?!

**Comment by GREENOVER** [comment]
@klmyoungyun 
아 또 발생안하네
숏스 다읽음 처리하면 0숏스말고 1숏스 등으로 카운팅 되야하는데 고게 안되었는데 지금은 또 정상이네?
일단 이슈 발생안하면 넘어가도될듯!
